DIM_LANDSCAPE = (7.25, 4.45)
DIM_PORTRAIT = (3.45, 4.45)
DIM_SQUARE = (4.45, 4.45)
IMG_PATH = "images/"
PATH_IMG_ATOMS = "images/atoms/"
PATH_IMG_POTENTIALS = "images/potentials/"
PATH_IMG_MAZES = "images/mazes/"
PATH_IMG_ANIMATIONS = "images/animations/"
PATH_IMG_TESTS = "images/tests/"
DATA_PATH = "data/"
PATH_DATA_MAZES = "data/mazes/"
PATH_MAZES_SUMMARY = "data/mazes_summaries/"
PATH_ENERGY_SUMMARY = "data/energy_summaries/"
PATH_ENERGY_SURFACES = "data/energy_surfaces/"
PATH_ENERGY_RATES = "data/sqra_rates_matrices/"
PATH_ENERGY_EIGEN = "data/sqra_eigenvectors_eigenvalues/"
PATH_ENERGY_GRIDS = "data/energy_grids/"
